Repository linc-technologies/.github, pull requests merged in 2022-10, with the labels that each got.

#22 fix(ember): add required build_num output to job
  .github/workflows/ember.yml
Labels: size/XS

#24 fix(workflows): set id for all steps to enable failure detection.
  .github/workflows/cli_build.yml
  .github/workflows/cli_release.yml
  .github/workflows/go.yml
  .github/workflows/go_module.yml
  .github/workflows/php.yml
Labels: size/M

#23 Feature/app-linting
  .github/workflows/ember.yml
Labels: size/M

#25 Feature/go 1.18
  .github/workflows/go.yml
  .github/workflows/go_module.yml
Labels: size/XS

#21 chore(deps): update helm to 3.10.0 to leverage install with `oci://` …
  .github/actions/deploy_helm/action.yml
Labels: size/XS

#26 chore(ember): lint all the apps!
  .github/workflows/ember.yml
Labels: size/XS

#27 feat: change workflows to only run on workflow_call
  .github/workflows/ember.yml
  .github/workflows/go.yml
  .github/workflows/go_module.yml
  .github/workflows/php.yml
Labels: size/XS

#29 feat(go): ensures go formatting is adhered to
  .github/workflows/go.yml
Labels: size/XS

#28 feat(go_module): ensures go formatting is adhered to
  .github/workflows/go_module.yml
Labels: size/XS

#30 feat(cli_build): ensures go formatting is adhered to
  .github/workflows/cli_build.yml
Labels: size/XS

#31 feat: add lint and go version matrix to go module
  .github/workflows/go_module.yml
Labels: size/S

#32 feat: add github actions dependabot.yml feed
  .github/dependabot.yml
Labels: size/XS

#35 fix: don't check for simplified go on format - this is the role of the lint checker.
  .github/workflows/cli_build.yml
  .github/workflows/go.yml
  .github/workflows/go_module.yml
Labels: size/XS

#39 chore: get the thing to prod.
  .github/workflows/ember.yml
Labels: size/S

#40 Revert "chore: get the thing to prod."
  .github/workflows/ember.yml
Labels: size/S

#41 Create CODEOWNERS
  CODEOWNERS
Labels: size/S

#42 fix(CODEOWNERS): fixes location of codeowners file.
  .github/CODEOWNERS
Labels: size/XS
